enum Colors {
	WHITE = "#FFFFFF",
	BLACK = "#000000",
	BUTTON_DISABLED_BG = "#f9f9f9",
	BUTTON_DISABLED_TEXT = "#acacac",
	TRANSPARENT = "transparent",
	ORANGE_DEFAULT = "#FF7020",
	ORANGE_HOVER = "#FFAB08",
	ORANGE_ACTIVE = "#F86310",
	WHITE_DEFAULT = "#F2F2F3",
	GRAY="#B1B1B1",
}

export default Colors;
